eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  currency-exchange:
    endpoints:
      endpoint:
        uri: http://currency-exchange/exchange/{baseCode}
